---
# Site Settings
title: ChinnoDog's Blog
# subtitle on page, description mostly for SEO
subtitle:
description: A compendium of all things tech.
email: ChinnoDog@lonesheep.net
github_username: ChinnoDog
minimal_mistakes_skin: dark
search: true
locale: en-US
title_separator: "-"
name: Stephen Nichols
repository: chinnodog/chinnodog.github.io
url: https://www.chinnodog.com
breadcrumbs: true
# lunr only indexes first 50 words of posts
lunr:
  search_within_pages: true

# Build Settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: "/:categories/:title/"
paginate: 5
paginate_path: "/page:num/"
timezone: America/New_York

include:
- _pages

# exclude:

plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache

author:
  name: Stephen Nichols
  avatar: images/chinnodog-photo.jpg
  bio: A nerd and a sailor, two things that go well together.
  location: Sarasota, FL
  email: ChinnoDog@lonesheep.net
  links:
  - label: Email
    icon: fas fa-fw fa-envelope-square
  - label: Website
    icon: fas fa-fw fa-link
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
  - label: Facebook
    icon: fab fa-fw fa-facebook-square
  - label: GitHub
    icon: fab fa-fw fa-github
  - label: Instagram
    icon: fab fa-fw fa-instagram
  bitbucket: ChinnoDog
  facebook: ChinnoDog
  foursquare: ChinnoDog
  github: ChinnoDog
  lastfm: ChinnoDog
  linkedin: stephen-nichols
  steam: chinnodog

footer:
  links:
  - label: Facebook
    icon: fab fa-fw fa-facebook-square
  - label: GitHub
    icon: fab fa-fw fa-github
  - label: Bitbucket
    icon: fab fa-fw fa-bitbucket

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"

comments:
  provider: disqus
  disqus:
    shortname: chinnodog
  discourse:
    server: 
  facebook:
    appid: 
    num_posts: 
    colorscheme: 

# Web integration
twitter:
  username: ChinnoDog
facebook:
  username: ChinnoDog
  app_id: 338998116184027
  publisher: https://www.facebook.com/ChinnoDog
# Open Graph default image - set this to a pic of me!
# og_image:

# Social profile info for search results
# social:
#   type:  # Person or Organization (defaults to Person)
#   name:  # If the user or organization name differs from the site's name
#   links:
#     - "https://twitter.com/yourTwitter"
#     - "https://www.facebook.com/yourFacebook"
#     - "https://instagram.com/yourProfile"
#     - "https://www.linkedin.com/in/yourprofile"

# TODO: Add analytics

# Enable compression
compress_html:
  clippings: all
  ignore:
    envs: development



# Do I need these?
# url: 
# baseurl: 
# teaser: 
# words_per_minute: 200
# staticman:
#   allowedFields: 
#   branch: 
#   commitMessage: 
#   filename: 
#   format: 
#   moderation: 
#   path: 
#   requiredFields: 
#   transforms:
#     email: 
#   generatedFields:
#     date:
#       type: 
#       options:
#         format: 
# reCaptcha:
#   siteKey: 
#   secret: 
# atom_feed:
#   path: 
# search_full_content: 
# search_provider: 
# algolia:
#   application_id: 
#   index_name: 
#   search_only_api_key: 
#   powered_by: 
# google:
#   search_engine_id: 
#   instant_search: 
# google_site_verification: 
# bing_site_verification: 
# yandex_site_verification: 
# naver_site_verification: 
# og_image: 
# social:
#   type: 
#   name: 
#   links: 
# analytics:
#   provider: false
#   google:
#     tracking_id: 
#     anonymize_ip: 
# keep_files:
# - ".git"
# - ".svn"
# encoding: utf-8
# markdown_ext: markdown,mkdown,mkdn,mkd,md
# highlighter: rouge
# lsi: false
# excerpt_separator: "\n\n"
# incremental: false
# kramdown:
#   input: GFM
#   hard_wrap: false
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   smart_quotes: lsquo,rsquo,ldquo,rdquo
#   enable_coderay: false
# sass:
#   sass_dir: _sass
#   style: compressed
# collections:
# posts:
#   title: Posts
#   output: true
# uploads:
#   title: Uploads
#   output: true
